# Generated by Django 5.0.3 on 2024-03-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='product',
            new_name='material_name',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='quantity',
            new_name='qty',
        ),
    ]
