# Generated by Django 5.0.3 on 2024-03-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_product_warehouse_material_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='price',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='qty',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.material'),
            preserve_default=False,
        ),
    ]
