# Generated by Django 5.0.3 on 2024-03-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_warehouse_material_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
