# Generated by Django 5.0.3 on 2024-03-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_materialdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdetail',
            name='charter',
            field=models.CharField(max_length=10),
        ),
    ]
