# Generated by Django 5.0.3 on 2024-03-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ordercount_material_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercount',
            name='material_name',
        ),
    ]
