# Generated by Django 5.0.3 on 2024-03-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ordercount_material_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable1', models.IntegerField(default=0)),
                ('variable2', models.IntegerField(default=0)),
                ('variable3', models.IntegerField(default=0)),
            ],
        ),
    ]
