# Generated by Django 5.0.3 on 2024-03-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_statute_variable4_statute_variable5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statute',
            name='variable2',
        ),
        migrations.RemoveField(
            model_name='statute',
            name='variable3',
        ),
        migrations.RemoveField(
            model_name='statute',
            name='variable4',
        ),
        migrations.RemoveField(
            model_name='statute',
            name='variable5',
        ),
        migrations.RemoveField(
            model_name='statute',
            name='variable6',
        ),
    ]
