# Generated by Django 5.0.3 on 2024-03-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_statute_variable2_statute_variable3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statute',
            name='variable1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statute',
            name='variable2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statute',
            name='variable3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statute',
            name='variable4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statute',
            name='variable5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statute',
            name='variable6',
            field=models.FloatField(default=0),
        ),
    ]
